Travel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.index, name = "index"),
#    url(r"^countries/$", views.countries, name = "countries"),
    url(r"^regions/$", views.regions, name = "regions"),
    url(r"^cities/(?P<region_id>[0-9]+)/$", views.cities, name = "cities"),
    url(r"^tour/(?P<tour_id>[0-9]+)/$", views.tours, name = "tours"),
    url(r"^discount_tours/$", views.discount_tours, name = "discount_tours"),
    url(r"^profile/$", views.profile, name="profile"),
    url(r"^bookings/$", views.bookings, name="bookings"),
    url(r"^add_booking/(?P<tour_id>[0-9]+)/$", views.add_booking, name = "add_booking"),
    url(r"^delete_booking/(?P<tour_id>[0-9]+)/$", views.delete_booking, name = "delete_booking")
]

Travel_agency/urls.py
from django.conf.urls import url, include
from Travel import views as Travel_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from Travel_agency import settings

urlpatterns = [
    url(r"^Travel/", include("Travel.urls")),
    url(r"^Travel/signup/$", Travel_views.signup, name="signup"),
    url(r"^Travel/login/$", auth_views.login, name="login"),
    url(r"^Travel/edit_profile/$", Travel_views.edit_profile, name="edit_profile"),
    url(r"^Travel/logout/$", auth_views.logout, name="logout"),
    url(r"^Travel/admin/", admin.site.urls),
    url(r"^$", RedirectView.as_view(url = "/Travel/")),
    url(r'^Travel/ckeditor/', include('ckeditor_uploader.urls')),
    url(r"^$", RedirectView.as_view(url = "/Travel/")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Travel/models.py
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

# Создание моделей.
class Region(models.Model):
    name = models.CharField('Регион', max_length=50)
    def __str__(self):
        return str(self.name)
    class Meta:
        verbose_name_plural="Регионы"
        verbose_name="регион"

class City(models.Model):
    region = models.ForeignKey(Region, verbose_name="Регион", null=True, blank=True)
    name = models.CharField('Населенный пункт', max_length=50)
    def __str__(self):
        return str(self.region) + ", " + str(self.name)
    class Meta:
        verbose_name_plural="населенные пункты"
        verbose_name="населенный пункт"

class Hotel(models.Model):
    name = models.CharField('Название', max_length=50)
    phone_regex = RegexValidator(regex=r'^\+7\s[(]{1}[0-9]{3}[)]{1}\s[0-9]{3}-{1}[0-9]{2}-{1}[0-9]{2}$')
    phone = models.CharField('Телефон', validators=[phone_regex], max_length=20, blank=True)
    comfort = models.PositiveIntegerField('Комфорт', default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    city = models.ForeignKey(City, verbose_name="Населенный пункт", null=True)
    address = models.CharField('Адрес', max_length=200)
    def __str__(self):
        return (str(self.name)
            + ", звезд: "
            + str(self.comfort)
            + ", г." 
            + str(self.city.name)
            + ", " 
            + str(self.address))
    class Meta:
        verbose_name_plural="гостиницы"
        verbose_name="гостиница"

class TourType(models.Model):
    name = models.CharField('Тип тура', max_length=50)
    def __str__(self):
        return str(self.name)
    class Meta: 
        verbose_name_plural = 'Типы тура'
        verbose_name = 'тип тура'

class Tour(models.Model):
    name = models.CharField('Название тура', max_length=50)
    type = models.ForeignKey(TourType, null=True, verbose_name='Тип тура')
    description = RichTextUploadingField('Описание тура')
    city = models.ForeignKey(City, null=True, verbose_name='Населенный пункт')
    date = models.DateField('Дата тура')
    days = models.PositiveIntegerField('Дней', default=1, validators=[MinValueValidator(1)])
    hotel = models.ForeignKey(Hotel, null=True, blank=True, verbose_name='Гостиница')
    hotel_price = models.PositiveIntegerField('Цена за номер', default=0)
    tour_price = models.PositiveIntegerField('Цена тура', default=0)
    discount = models.PositiveIntegerField('Скидка', default=0, validators=[MaxValueValidator(100)])
    def __str__(self):
        if self.discount>0:
            if self.hotel is None:
                price=self.tour_price*(100-self.discount)/100
                return (
                    str(self.name)
                    + ', '
                    + str(self.date.strftime('%d.%m.%Y'))
                    + ', дней: '
                    + str(self.days)
                    + ', скидка: '
                    + str(self.discount)
                    + '%, '
                    + str(int(price))
                    + 'руб.')
            else:
                price=(self.tour_price+self.hotel_price*self.days)*(100-self.discount)/100
                return (
                    str(self.name)
                    + ', '
                    + str(self.date.strftime('%d.%m.%Y'))
                    + ', дней: '
                    + str(self.days)
                    + ', '
                    + str(self.hotel.name)
                    + ', скидка: '
                    + str(self.discount)
                    + '%, '
                    + str(int(price))
                    + 'руб.')
        else:
            if self.hotel is None:
                return (
                    str(self.name)
                    + ', '
                    + str(self.date.strftime('%d.%m.%Y'))
                    + ', дней: '
                    + str(self.days)
                    + ', '
                    + str(self.tour_price)
                    + 'руб.')
            else:
                price=self.tour_price+self.hotel_price*self.days
                return (
                    str(self.name)
                    + ', '
                    + str(self.date.strftime('%d.%m.%Y'))
                    + ', дней: '
                    + str(self.days)
                    + ', '
                    + str(self.hotel.name)
                    + ', '
                    + str(int(price))
                    + 'руб.')
    class Meta:
        verbose_name_plural='Туры'
        verbose_name='тур'

class Manager(models.Model):
    username = models.OneToOneField(User, verbose_name="Пользователь")
    patronymic = models.CharField('Отчество', blank=True, max_length=50)
    birthday = models.DateField('Дата рождения')
    address = models.CharField('Адрес', max_length=200)
    phone_regex = RegexValidator(regex=r'^\+7\s[(]{1}[0-9]{3}[)]{1}\s[0-9]{3}-{1}[0-9]{2}-{1}[0-9]{2}$')
    phone = models.CharField('Телефон', validators=[phone_regex], max_length=20, blank=True)
    def __str__(self):
        return (str(self.username) 
            + " "
            + str(self.patronymic)
            + ", дата рождения: " 
            + str(self.birthday.strftime("%d.%m.%Y")) 
            + ", "
            + str(self.phone))
    class Meta:
        verbose_name_plural="Менеджеры"
        verbose_name='менеджер'

class Tourist(models.Model):
    username = models.OneToOneField(User, verbose_name="Пользователь")
    patronymic = models.CharField('Отчество', blank=True, max_length=50)
#    birthday = models.DateField('Дата рождения', blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+7\s[(]{1}[0-9]{3}[)]{1}\s[0-9]{3}-{1}[0-9]{2}-{1}[0-9]{2}$')
    phone = models.CharField('Телефон', validators=[phone_regex], max_length=20, blank=True)
    def __str__(self):
        return (
            str(self.username) 
            + " "
            + str(self.patronymic)
            #+ ", дата рождения: " 
            #+ str(self.birthday.strftime("%d.%m.%Y")) 
            + ', '
            + str(self.phone))
    class Meta:
        verbose_name_plural="Туристы"
        verbose_name='турист'

class TourBooking(models.Model):
    tourist = models.ForeignKey(Tourist, blank=True, verbose_name='Турист')
    last_name = models.CharField('Фамилия', max_length=50)
    first_name = models.CharField('Имя', max_length=50)
    patronymic = models.CharField('Отчество', blank=True, max_length=50)
    phone_regex = RegexValidator(regex=r'^\+7\s[(]{1}[0-9]{3}[)]{1}\s[0-9]{3}-{1}[0-9]{2}-{1}[0-9]{2}$')
    phone = models.CharField('Телефон', validators=[phone_regex], max_length=20, blank=True)
    tour = models.ForeignKey(Tour, null=True, verbose_name='Выбранный тур')
    manager = models.ForeignKey(Manager, null=True, verbose_name='менеджер')
    approved = models.BooleanField(default=False, verbose_name='Подтверждение')
    cancel = models.BooleanField(default=False, blank=True, verbose_name='Отмена')
    message = models.CharField('Причина отмены', max_length=50, blank=True)
    def __str__(self):
        if self.approved is True:
            return (str(self.last_name)
                + ' '
                + str(self.first_name)
                + ' '
                + str(self.patronymic)
                + ', '
                + str(self.phone)
                + ', '
                + str(self.tour)
                + ', подтверждено')
        elif self.cancel is True:
            return (str(self.last_name)
                + ' '
                + str(self.first_name)
                + ' '
                + str(self.patronymic)
                + ', '
                + str(self.phone)
                + ', '
                + str(self.tour)
                + 'отменено. '
                + str(self.message))
        else:
            return (str(self.last_name)
                + ' '
                + str(self.first_name)
                + ' '
                + str(self.patronymic)
                + ', '
                + str(self.phone)
                + ', '
                + str(self.tour)
                + ', не подтверждено')
    class Meta:
        verbose_name_plural="Бронирования туров"
        verbose_name = "бронирование тура"

@receiver(post_save, sender=User)
def create_tourist(sender, instance, created, **kwargs):
    if created:
        Tourist.objects.create(username=instance)

@receiver(post_save, sender=User)
def save_tourist(sender, instance, **kwargs):
    instance.tourist.save()

def user_full_name(self):
    return '%s %s' % (self.last_name, self.first_name)

User.__str__ = user_full_name

Travel/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from Travel.forms import SignupForm, EditForm
from Travel.models import *

def index(request):
    if request.user.is_staff:
        return redirect('/Travel/admin')
    else:
        return render(
            request, 
            "Travel/index.html", 
            {
                "Travel": True
            }
        )
        
def regions(request):
    regions = Region.objects.all()
    return render(
        request, 
        "Travel/regions.html", 
        {
            "regions": regions
        }
    )

def cities(request, region_id):
    region = Region.objects.get(id = region_id)
    cities = region.city_set.all()
    return render(
        request, 
        "Travel/cities.html", 
        {
            "cities": cities
        }
    )

def tours(request, tour_id):
    tour = Tour.objects.get(id = tour_id)
    # Цена за тур и гостиницу по скидке 
    discount_price = (tour.days * tour.hotel_price + tour.tour_price) * (100 - tour.discount) / 100
    # Цена за тур и гостиницу без скидки 
    price = tour.days * tour.hotel_price + tour.tour_price
    # Цена за тур без гостиницы cо скидкой
    discount_tour_price = tour.tour_price * (100 - tour.discount) / 100
    booking = None
    if not request.user.is_anonymous:
        tourist_id = request.user.tourist.id
        try:
            booking = TourBooking.objects.get(
                tour__id = tour_id, 
                tourist__id = tourist_id
            )
        except TourBooking.DoesNotExist:
            pass
    return render(request, 
        "Travel/tour.html", 
        {
            "tour": tour,
            "discount_price": discount_price,
            "price": price, 
            "discount_tour_price": discount_tour_price,
            "booking": booking,
        }
    )

def discount_tours(request):
    discount_tours = Tour.objects.all().exclude(discount = 0)
    return render(
        request, 
        "Travel/discount_tours.html", 
        {
            "discount_tours": discount_tours
        }
    )

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(
                username = username, 
                password = raw_password
            )
            login(request, user)
            return redirect("edit_profile")
    else:
        form = SignupForm()
    return render(
        request, 
        "registration/signup.html", 
        {
            "form": form
        }
    )

def edit_profile(request):
    if request.method == "POST":
        edit_user = EditForm(
            request.POST, 
            instance = request.user
        )
        edit_profile = EditForm(
            request.POST, 
            instance = request.user.tourist
        )
        if edit_user.is_valid() and edit_profile.is_valid():
            edit_user.save()
            edit_profile.save()
            request.user.tourist.patronymic
            #request.user.tourist.birthday
            request.user.tourist.phone
            return redirect("profile")
    else:
        edit_user = EditForm()
        edit_profile = EditForm()
    return render(
        request, 
        "registration/edit_profile.html",
        {
            "edit_user": edit_user, 
            "edit_profile": edit_profile
        }
    )

    cities=region.city_set.all()
    return render(request, "Travel/cities.html", {"cities": cities})

def tours(request, tour_id):
    tour = Tour.objects.get(id = tour_id)
    # Цена за тур и гостиницу по скидке 
    discount_price=(tour.days*tour.hotel_price+tour.tour_price)*(100-tour.discount)/100
    # Цена за тур и гостиницу без скидки 
    price=tour.days*tour.hotel_price+tour.tour_price
    # Цена за тур без гостиницы cо скидкой
    discount_tour_price=tour.tour_price*(100-tour.discount)/100
    booking=None
    if not request.user.is_anonymous:
        tourist_id=request.user.tourist.id
        try:
            booking=TourBooking.objects.get(tour__id=tour_id, tourist__id=tourist_id)
        except TourBooking.DoesNotExist:
            pass
    return render(request, 
        'Travel/tour.html', 
        {'tour': tour,
            'discount_price': discount_price,
            'price': price, 
            'discount_tour_price': discount_tour_price,
            'booking': booking,
        }
    )

def discount_tours(request):
    discount_tours = Tour.objects.all().exclude(discount = 0)
    return render(request, 'Travel/discount_tours.html', {'discount_tours':discount_tours})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('edit_profile')
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})

def profile(request):
    tourist=request.user.tourist
    return render(request, 'Travel/profile.html', {'profile':True})

def edit_profile(request):
    if request.method == 'POST':
        edit_user = EditForm(request.POST, instance=request.user)
        edit_profile = EditForm(request.POST, instance=request.user.tourist)
        if edit_user.is_valid() and edit_profile.is_valid():
            edit_user.save()
            edit_profile.save()
            request.user.tourist.patronymic
            #request.user.tourist.birthday
            request.user.tourist.phone
            return redirect('profile')
    else:
        edit_user = EditForm()
        edit_profile = EditForm()
    return render(request, 'registration/edit_profile.html', {'edit_user': edit_user, 'edit_profile': edit_profile})

def bookings(request):
    tourist_id=request.user.tourist.id
    booking=TourBooking.objects.all().filter(tourist__id=tourist_id)
    return render(request, 'Travel/bookings.html', {'booking':booking, 'bookings':True})

def add_booking(request, tour_id):
    tour=Tour.objects.get(id=tour_id)
    tourist=request.user.tourist
    last_name = request.user.last_name
    first_name = request.user.first_name
    patronymic = request.user.tourist.patronymic
    phone = request.user.tourist.phone
    TourBooking.objects.create(tour=tour, tourist=tourist, last_name=last_name, first_name=first_name, patronymic=patronymic, phone=phone)
    return redirect('bookings')

def delete_booking(request, tour_id):
    tour=Tour.objects.get(id=tour_id)
    tourist=request.user.tourist
    TourBooking.objects.get(tour=tour, tourist=tourist).delete()
    return redirect('bookings')

Travel/templates/Travel/bookings.html
{% extends "base.html" %}
{% block title %}
    Мои туры
{% endblock title %}
{% block content %}
    <h2>Мои туры</h2>
    {% if booking %} <!-- если есть бронирование -->
        <table class="table table-striped table-bordered">
            <tr>
                <th>Тур</th>
                <th style="width:20%">Статус</th>
            </tr>
            {% for tour_info in booking %}
                <tr>
                    <td>
                        <a href="/Travel/tour/{{ tour_info.tour.id }}" title="Нажмите, чтобы перейти к туру">
                            {{ tour_info.tour.name }}, {{tour_info.tour.date}}
                        </a>
                    </td>
                    <td>
                        {% if not tour_info.approved and not tour_info.cancel %}
                           Ожидается подтверждение заяки менеджером.<br>
							<form action="/Travel/delete_booking/{{tour_info.id}}">
								<input type="submit" value="Отменить бронирование">
							</form>
                        {% elif tour_info.approved %}
                            <button>Оплатить</button><br>
                        {% else %}
                            Отменено
                            <br>
                            {{tour_info.message}}.
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %} <!-- Иначе -->
        <h3>Пока, вы не забронировали ни один тур.</h3>
    {% endif %}
{% endblock content %}

Travel/templates/Travel/cities.html
{% extends "base.html" %}
{% block title %}
	Туры
{% endblock %}
{% block content %}
	<h2>
		Туры
	</h2>
	{% for city in cities %}
        {% for tour in city.tour_set.all %}
            {% if not tour %}
                В данном городе пока нет туров.
            {% else %}
                {% if tour.discount > 0 %}
                    <a href="/Travel/tour/{{ tour.id }}" title="Нажмите чтобы узнать подробнее">
                        <font color="red">
                            <i style="font-size:20px;">Акция! </i>
                            {{ tour }}
                        </font>
                        <br>
                    </a>
                {% else %}
                    <a href="/Travel/tour/{{tour.id}}">{{ tour }}</a>
                    <br>
                {% endif %}
            {% endif %}
		{% endfor %}
	{% endfor %}
{% endblock %}

Travel/templates/Travel/discount_tours.html
{% extends "base.html" %}
{% block title %}
    Туры со скидкой
{% endblock title %}
{% block content %}
    <h2>Туры со скидкой</h2>
    {% for tour in discount_tours %}
		<a href="/Travel/tour/{{ tour.id }}" title="Нажмите чтобы узнать подробнее">
			<font color="red">
				<i style="font-size:20px;">Акция! </i>
				{{ tour }}.
			</font>
			<br>
		</a>
    {% endfor %}
{% endblock content %}

Travel/templates/Travel/home.html
{% extends 'base.html' %}
{% block title %}
	Главная
{% endblock %}
{% block content %}
	{% if user.is_anonymous %}
		<h2>Добро пожаловать гость!</h2>
		Для того, чтобы отправиться в путешествие вам необходимо выполнить 5 простых условий: 
		<ul>
			<li>
				1) Зарегистрироваться заполнив простую форму.<br>
				2) Выбрать имеющийся тур из каталога.<br>
				3) Забронировать тур.<br>
				4) Дождаться подтверждения бронирования.<br>
				5) Оплатить тур и наслаждаться отдыхом.
			</li>
		</ul>
	{% elif user.tourist %}
		<h2>Здравствуйте {{user.first_name}} {{user.last_name}}!</h2>
	{% else %}
	{% endif %}
{% endblock %}

Travel/templates/Travel/index.html
{% extends 'base.html' %}
{% block title %}
	Главная
{% endblock %}
{% block content %}
	{% if user.is_anonymous %}
		<h2>Добро пожаловать гость!</h2>
		Для того, чтобы отправиться в путешествие вам необходимо выполнить 5 простых условий: 
		<ul>
			<li>
				1) Зарегистрироваться заполнив простую форму.<br>
				2) Выбрать имеющийся тур из каталога.<br>
				3) Забронировать тур.<br>
				4) Дождаться подтверждения бронирования.<br>
				5) Оплатить тур.
			</li>
		</ul>
	{% elif user.tourist %}
		<h2>Здравствуйте {{user.first_name}} {{user.tourist.patronymic}}!</h2>
		<i style="font-size: 16px;"><b>Турфирма «ОстровОК-Тур» готова предложить вам туры в большинство городов России. Круглый год мы предлагаем туры со скидками, завоевавшими признание миллионов туристов.
		У нас вы сможете найти туры на любой вкус.
		Мы рекомендуем туры в Геленджик, Анапу, Сочи, где вы можете испытать насыщенный и зажигательный отдых. Сторонникам мягкого климата, теплого моря и пляжей турфирма ОстровОК-Тур» и для романтичного отдыха с вашей второй половинкой лучше всего подойдет тур в Санкт-Петербург.
		Турфирма «ОстровОК-Тур» — находка для желающих отдохнуть комфортно и со вкусом.
		Мы знаем, как сделать ваш отдых приятным, полезным и насыщенным! Обращаясь в офис нашей турфирмы вы поручаете свой отдых профессионалам. Мы подберем максимально соответствующий вашим запросам тур, который подарит массу положительных эмоций и незабываемых впечатлений.
		Выберите тип отдыха, который вам по душе!</b></i>
	{% else %}
	{% endif %}
{% endblock %}

Travel/templates/Travel/my_profile.html
{% extends "base.html" %}
{% block title %}
    Мой профиль
{% endblock title %}
{% block content %}
    <h2>Мой профиль</h2>
    <table border="2" align='center' style="border-collapse: collapse; width: 30%">
        <tr>
            <th>Фамилия:</th>
            <td style="width: 60%;">
                {{user.last_name}}
            </td>
        </tr>
        <tr>
            <th>Имя:</th>
            <td style="width: 60%;">
                {{user.first_name}}
            </td>
        </tr>
        <tr>
            <th>Отчество:</th>
            <td style="width: 60%;">
                {{request.user.tourist.patronymic}}
            </td>
        </tr>
        <tr>
            <th>Номер телефона:</th>
            <td style="width: 60%;">
                {{request.user.tourist.phone}}
            </td>
        </tr>
        <tr>
            <th>Почта:</th>
            <td style="width: 60%;">
                {{user.email}}
            </td>
        </tr>
        <tr>
            <th colspan="2">
                <a href="{% url 'change_profile' %}">
                    <button style="width: 100%;">Изменить</button>
                </a>
            </th>
        </tr>
    </table>
{% endblock content %}

Travel/templates/Travel/my_tours.html
{% extends "base.html" %}
{% block title %}
    Личный кабинет
{% endblock title %}
{% block content %}
    <h2 align="center">Ваши туры</h2>
    {% if booking %} <!-- если есть бронирование -->
        <table border="2" class="content" style="border-collapse: collapse;">
            <tr>
                <th>
                    Тур
                </th>
                <th style="width:20%">
                    Статус заказа
                </th>
            </tr>
            {% for tour_info in booking %}
                <tr>
                    <td>
                        <a href="/Travel/tour/{{ tour_info.tour.id }}" title="Нажмите, чтобы перейти к туру">
                            {{ tour_info.tour }}
                        </a>
                    </td>
                    {% if not tour_info.approved %}
                        <td>
                            Ожидается подтверждение
                        </td>
                    {% else %}
                        <td align="center">
                            <button>Оплатить</button>
                            <form action="/Travel/delete_booking_tour/{{tour_info.tour.id}}">
                                <br>
                                <input type="submit" value="Отменить">
                             </form>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %} <!-- Иначе -->
        <h3>Пока, вы не забронировали ни один тур.</h3>
    {% endif %}
{% endblock content %}

Travel/templates/Travel/profile.html
{% extends "base.html" %}
{% block title %}
    Мой профиль
{% endblock title %}
{% block content %}
<div class="container">
	<div class="row main-form">
		<div class="form-group">
			<h3>Мой профиль</h3>
			<label class="cols-sm-2 control-label">Фамилия</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-user" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.last_name }}" disabled>
				</div>
			</div>
		</div>
			
		<div class="form-group">
			<label class="cols-sm-2 control-label">Имя</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-user" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.first_name }}" disabled>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label class="cols-sm-2 control-label">Отчество</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-user" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.tourist.patronymic }}" disabled>
				</div>
			</div>
		</div>

		<!--<div class="form-group">
			<label class="cols-sm-2 control-label">Дата рождения</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-gift" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.tourist.birthday|date:'d.m.Y' }}" disabled>
				</div>
			</div>
		</div>-->

		<div class="form-group">
			<label class="cols-sm-2 control-label">Телефон</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-phone" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.tourist.phone }}" disabled>
				</div>
			</div>
		</div>
			
		<div class="form-group">
			<label class="cols-sm-2 control-label">Email</label>
			<div class="cols-sm-10">
				<div class="input-group">
					<span class="input-group-addon">
						<i class="fa fa-envelope" aria-hidden="true"></i>
					</span>
					<input class="form-control" value="{{ request.user.email }}" disabled>
				</div>
			</div>
		</div>

		<div class="form-group ">
				<a href="{% url 'edit_profile' %}">
					<button	class="btn btn-primary btn-lg btn-block login-button">Редактировать</button>
				</a>
			</div>
		</div>
	</div>
{% endblock content %}

Travel/templates/Travel/region_cities.html
{% extends "base.html" %}
{% block title %}
	Туры
{% endblock %}
{% block content %}
	<h2 align="center">
		Туры
	</h2>
	{% for city in cities %}
		{% for tour in city.tour_set.all %}
			{% if tour.hotel is None %}
                {% if tour.sale > 0 %}
					<a href="/Travel/tour/{{ tour.id }}" title="Нажмите чтобы узнать подробнее">
						<font color="red">
							<i style="font-size:20px;">Акция! </i>
							{{ tour.name }}, {{ city.name }}, {{ tour.type }} тур, {{ tour.date }}.
						</font>
						<br>
					</a>
                {% else %}
					<a href="/Travel/tour/{{ tour.id }}" title="Нажмите чтобы узнать подробнее">
						{{ tour.name }}, {{ city.name }}, {{ tour.type }} тур, {{ tour.date }}.
						<br>
					</a>
                {% endif %}
			{% else %}
				<a href="/Travel/tour/{{ tour.id }}" title="Нажмите чтобы узнать подробнее">
					{{ tour.name }}, {{ city.name }}, {{ tour.type }} тур, {{ tour.hotel.name }}, {{ tour.date }}.
					<br>
				</a>
			{% endif %}
		{% endfor %}
	{% endfor %}
{% endblock %}

Travel/templates/Travel/regions.html
{% extends "base.html" %}
{% block title %}
	Страны и регионы
{% endblock %}
{% block content %}
	<h2>
		Выберите направление
	</h2>
	<ul style="font-size: 18px;">
		{% for region in regions %}
			<a href="/Travel/cities/{{region.id}}">
				- {{ region.name }}<br>
			</a>
		{% endfor %}
	</ul>
{% endblock %}